<?xml version="1.0"?>
<robot name="test_bot"
	xmlns:xacro="http://www.ros.org/wiki/xacro">
	<xacro:include filename="common_properties.xacro" />
	<!--<xacro:include filename="test_bot_gazebo.xacro" />-->
	<xacro:property name="base_length"
		value="0.8" />
	<xacro:property name="base_width"
		value="0.4" />
	<xacro:property name="base_height"
		value="0.08" />
	<xacro:property name="wheel_radius"
		value="0.12" />
	<xacro:property name="wheel_length"
		value="0.08" />
	<!--Ebox = Electrical box-->
	<xacro:property name="Ebox_length"
		value="0.1" />
	<xacro:property name="Ebox_width"
		value="0.4" />
	<xacro:property name="Ebox_height"
		value="0.25" />
	<xacro:property name="lidar_radius"
		value="0.04" />
	<xacro:property name="lidar_height"
		value="0.04" />
	<!--<xacro:property name="camera_length"
		value="0.015" />
	<xacro:property name="camera_width"
		value="0.130" />
	<xacro:property name="camera_height"
		value="0.022" />
	<xacro:property name="camera_pole_length"
		value="0.02" />
	<xacro:property name="camera_pole_width"
		value="0.02" />
	<xacro:property name="camera_pole_height"
		value="0.7" />-->
	<link name="base_footprint" />
	<!--<link name="odom" />
	<link name="map" />-->
	<link name="base_link">
		<visual>
			<geometry>
				<box size="${base_length} ${base_width} ${base_height}" />
			</geometry>
			<origin xyz="0 0 ${base_height / 2}"
				rpy="0 0 0" />
			<material name="grey" />
		</visual>
		<collision>
			<geometry>
				<box size="${base_length} ${base_width} ${base_height}" />
			</geometry>
			<origin xyz="0 0 ${base_height / 2}"
				rpy="0 0 0" />
		</collision>
		<!--<xacro:box_inertia m="7.0"
			l="${base_length}"
			w="${base_width}"
			h="${base_height}"
			xyz="0 0 ${base_height / 2}"
			rpy="0 0 0" />-->
	</link>
	<xacro:macro name="wheel_link"
		params="prefix">
		<link name="${prefix}_wheel_link">
			<visual>
				<geometry>
					<cylinder radius="${wheel_radius}"
						length="${wheel_length}" />
				</geometry>
				<origin xyz="0 0 0"
					rpy="${pi / 2.0} 0 0" />
				<material name="blue" />
			</visual>
			<collision>
				<geometry>
					<cylinder radius="${wheel_radius}"
						length="${wheel_length}" />
				</geometry>
				<origin xyz="0 0 0"
					rpy="${pi / 2.0} 0 0" />
			</collision>
			<!--<xacro:cylinder_inertia m="1.5"
				r="${wheel_radius}"
				h="${wheel_length}"
				xyz="0 0 0"
				rpy="${pi / 2.0} 0 0" />-->
		</link>
	</xacro:macro>
	<xacro:wheel_link prefix="front_right" />
	<xacro:wheel_link prefix="front_left" />
	<xacro:wheel_link prefix="rear_right" />
	<xacro:wheel_link prefix="rear_left" />
	<link name="Ebox_link">
		<visual>
			<geometry>
				<box size="${Ebox_length} ${Ebox_width} ${Ebox_height}" />
			</geometry>
			<origin xyz="0 0 0"
				rpy="0 0 0" />
			<material name="grey" />
		</visual>
		<collision>
			<geometry>
				<box size="${Ebox_length} ${Ebox_width} ${Ebox_height}" />
			</geometry>
			<origin xyz="0 0 0"
				rpy="0 0 0" />
		</collision>
		<!--<xacro:box_inertia m="2.0"
			l="${Ebox_length}"
			w="${Ebox_width}"
			h="${Ebox_height}"
			xyz="0 0 0"
			rpy="0 0 0" />-->
	</link>
	<!--<link name="camera_pole_link">
		<visual>
			<geometry>
				<box size="${camera_pole_length} ${camera_pole_width} ${camera_pole_height}" />
			</geometry>
			<origin xyz="0 0 0"
				rpy="0 0 0" />
			<material name="grey" />
		</visual>
		<collision>
			<geometry>
				<box size="${camera_pole_length} ${camera_pole_width} ${camera_pole_height}" />
			</geometry>
			<origin xyz="0 0 0"
				rpy="0 0 0" />
		</collision>
		<xacro:box_inertia m="1.0"
			l="${camera_pole_length}"
			w="${camera_pole_width}"
			h="${camera_pole_height}"
			xyz="0 0 0"
			rpy="0 0 0" />
	</link>-->
	<link name="lidar_link">
		<visual>
			<geometry>
				<cylinder radius="${lidar_radius}"
					length="${lidar_height}" />
			</geometry>
			<origin xyz="0 0 0"
				rpy="0 0 0" />
			<material name="green" />
		</visual>
		<collision>
			<geometry>
				<cylinder radius="${lidar_radius}"
					length="${lidar_height}" />
			</geometry>
		</collision>
		<!--<xacro:cylinder_inertia m="0.1"
			r="${lidar_radius}"
			h="${lidar_height}"
			xyz="0 0 0"
			rpy="0 0 0" />-->
	</link>
	<!--<link name="camera_link">
		<visual>
			<origin xyz="0 0 0"
				rpy="0 0 0" />
			<geometry>
				<box size="${camera_length} ${camera_width} ${camera_height}" />
			</geometry>
			<material name="green" />
		</visual>
		<collision>
			<origin xyz="0 0 0"
				rpy="0 0 0" />
			<geometry>
				<box size="${camera_length} ${camera_width} ${camera_height}" />
			</geometry>
		</collision>
		<xacro:box_inertia m="0.1"
			l="${camera_length}"
			w="${camera_width}"
			h="${camera_height}"
			xyz="0 0 0"
			rpy="0 0 0" />
	</link>
	<link name="camera_depth_frame"/>
	<link name="imu_link">
		<visual>
			<geometry>
				<box size="0.05 0.05 0.05" />
			</geometry>
			<origin xyz="0 0 0"
				rpy="0 0 0" />
			<material name="green" />
		</visual>
		<collision>
			<geometry>
				<box size="0.05 0.05 0.05" />
			</geometry>
		</collision>
		<xacro:box_inertia m="0.1"
			l="0.05"
			w="0.05"
			h="0.05"
			xyz="0 0 0"
			rpy="0 0 0" />
	</link>
	<joint name="odom_map"
		type="fixed">
		<parent link="map" />
		<child link="odom" />
		<origin xyz="0 0 0"
			rpy="0 0 0" />
	</joint>
	<joint name="base_link_odom"
		type="fixed">
		<parent link="odom" />
		<child link="base_link" />
		<origin xyz="0 0 0"
			rpy="0 0 0" />
	</joint>-->
	<joint name="base_joint"
		type="fixed">
		<parent link="base_link" />
		<child link="base_footprint" />
		<origin xyz="0 0 ${-wheel_radius}"
			rpy="0 0 0" />
	</joint>
	<joint name="base_rear_right_wheel_joint"
		type="fixed">
		<parent link="base_link" />
		<child link="rear_right_wheel_link" />
		<origin xyz="${-base_length / 4.0} ${-(base_width + wheel_length) / 2.0} 0"
			rpy="0 0 0" />
		<!--<axis xyz="0 1 0" />-->
	</joint>
	<joint name="base_rear_left_wheel_joint"
		type="fixed">
		<parent link="base_link" />
		<child link="rear_left_wheel_link" />
		<origin xyz="${-base_length / 4.0} ${(base_width + wheel_length) / 2.0} 0"
			rpy="0 0 0" />
		<!--<axis xyz="0 1 0" />-->
	</joint>
	<joint name="base_front_right_wheel_joint"
		type="fixed">
		<parent link="base_link" />
		<child link="front_right_wheel_link" />
		<origin xyz="${base_length / 4.0} ${-(base_width + wheel_length) / 2.0} 0"
			rpy="0 0 0" />
	</joint>
	<joint name="base_front_left_wheel_joint"
		type="fixed">
		<parent link="base_link" />
		<child link="front_left_wheel_link" />
		<origin xyz="${base_length / 4.0} ${(base_width + wheel_length) / 2.0} 0"
			rpy="0 0 0" />
	</joint>
	<joint name="base_Ebox_joint"
		type="fixed">
		<parent link="base_link" />
		<child link="Ebox_link" />
		<origin xyz="${(-base_length / 2) - (Ebox_length / 2)} 0 ${Ebox_height / 2}"
			rpy="0 0 0" />
	</joint>
	<!--<joint name="base_camera_pole_joint"
		type="fixed">
		<parent link="base_link" />
		<child link="camera_pole_link" />
		<origin xyz="${(base_length / 2) - (2*lidar_radius) - (camera_pole_length/2)} 0 ${(base_height/2) + (camera_pole_height/2)}"
			rpy="0 0 0" />
	</joint>-->
	<joint name="base_lidar_joint"
		type="fixed">
		<parent link="base_link" />
		<child link="lidar_link" />
		<origin xyz="${(base_length/2) - lidar_radius} 0 ${base_height + (lidar_height/2)}"
			rpy="0 0 0" />
	</joint>
	<!--<joint name="base_camera_joint"
		type="fixed">
		<parent link="base_link" />
		<child link="camera_link" />
		<origin xyz="${(base_length / 2) - (2*lidar_radius) - (camera_pole_length/2)} 0 ${(base_height/2) + (camera_pole_height) + (camera_height/2)}"
			rpy="0 0 0" />
	</joint>
	<joint name="camera_depth_joint" type="fixed">
		<origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
		<parent link="camera_link"/>
		<child link="camera_depth_frame"/>
	</joint>
	<joint name="base_imu_joint"
		type="fixed">
		<parent link="base_link" />
		<child link="imu_link" />
		<origin xyz="0 0 ${base_height + 0.025}"
			rpy="0 0 0" />
	</joint>-->
</robot>