<?xml version="1.0"?>
<robot name="test_bot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="common_properties.xacro" />

    <xacro:property name="base_length" value="1.0" />
    <xacro:property name="base_width" value="0.5" />
    <xacro:property name="base_height" value="0.08" />
    <xacro:property name="wheel_radius" value="0.15" />
    <xacro:property name="wheel_length" value="0.1" />
    <xacro:property name="Ebox_length" value="0.1" /> <!--Ebox = Electrical box-->
    <xacro:property name="Ebox_width" value="0.5" />
    <xacro:property name="Ebox_height" value="0.3" />

    <link name="base_footprint" />

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2}" rpy="0 0 0" />
            <material name="grey" />
        </visual>
    </link>

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <material name="blue" />
            </visual>
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="front_right" />
    <xacro:wheel_link prefix="front_left" />
    <xacro:wheel_link prefix="rear_right" />
    <xacro:wheel_link prefix="rear_left" />

    <link name="Ebox_link">
        <visual>
            <geometry>
                <box size="${Ebox_length} ${Ebox_width} ${Ebox_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="grey" />
        </visual>
    </link>
    
    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <joint name="base_rear_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="rear_right_wheel_link" />
        <origin xyz="${-base_length / 4.0} ${-(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_rear_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="rear_left_wheel_link" />
        <origin xyz="${-base_length / 4.0} ${(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_front_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="front_right_wheel_link" />
        <origin xyz="${base_length / 4.0} ${-(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_front_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="front_left_wheel_link" />
        <origin xyz="${base_length / 4.0} ${(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_Ebox_joint" type="fixed">
        <parent link="base_link" />
        <child link="Ebox_link" />
        <origin xyz="${-base_length / 2} 0 ${Ebox_height / 2}" rpy="0 0 0" />
    </joint>

</robot>