scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: angle
      type: laser_filters/LaserScanAngularBoundsFilterInPlace
      params:
        # got rid of the laser filter, you can just put an object very close behind lidar and it won't track it
        
        #lower_angle: -1.57079632679
        #upper_angle: 1.57079632679
        lower_angle: -3.14159265359
        upper_angle: 3.14159265359
